// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDowrH1xjy9TZWcMQc2wl-sNDCCAf7Qsyg',
    appId: '1:690801611214:web:9dcc616cac1405065e9b9f',
    messagingSenderId: '690801611214',
    projectId: 'certain-math-466020-a1',
    authDomain: 'certain-math-466020-a1.firebaseapp.com',
    storageBucket: 'certain-math-466020-a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZxJJIWHVHFVkfgOMMRgFCjvh5mWJWbs',
    appId: '1:690801611214:android:34ddbd42d8a405bd5e9b9f',
    messagingSenderId: '690801611214',
    projectId: 'certain-math-466020-a1',
    storageBucket: 'certain-math-466020-a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApW8uCkALnKz9e9I2Ld3H-G63XgzIsues',
    appId: '1:690801611214:ios:eef1c01dc3d793be5e9b9f',
    messagingSenderId: '690801611214',
    projectId: 'certain-math-466020-a1',
    storageBucket: 'certain-math-466020-a1.firebasestorage.app',
    iosBundleId: 'com.example.skrola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApW8uCkALnKz9e9I2Ld3H-G63XgzIsues',
    appId: '1:690801611214:ios:eef1c01dc3d793be5e9b9f',
    messagingSenderId: '690801611214',
    projectId: 'certain-math-466020-a1',
    storageBucket: 'certain-math-466020-a1.firebasestorage.app',
    iosBundleId: 'com.example.skrola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDowrH1xjy9TZWcMQc2wl-sNDCCAf7Qsyg',
    appId: '1:690801611214:web:0a59e0c89035b25f5e9b9f',
    messagingSenderId: '690801611214',
    projectId: 'certain-math-466020-a1',
    authDomain: 'certain-math-466020-a1.firebaseapp.com',
    storageBucket: 'certain-math-466020-a1.firebasestorage.app',
  );
}
